name: Generate Daily Newspaper

on:
  push:
    branches:
      - feature/movie-poster
  schedule:
    - cron: "15 13 * * *" # (or '15 1 * * *' for the newspaper)
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y chromium-browser

      - name: Generate Newspaper
        run: python generate.py

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add newspaper.png
          git commit -m "Auto-update daily newspaper" || echo "No changes to commit"
          git push
